# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: skywarth/vite-github-pages-deployer@v1.2.0
    - name : Vite Github Pages Deployer
      with :
          public_base_path: ${{ github.event.repository.name }}
          build_path: ./dist
          install_phase_node_env:  dev
          build_phase_node_env: production
          package_manager:  npm
          artifact_name: github-pages
          debug_mode: false
          
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
